name: Feature request
description: Suggest an idea for VitaDB
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Is your request related to something that's currently annoying or missing?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
    validations:
      required: false
